Update README.md
Hi-Folks/statistics pull request #63
Opened 2023-10-30 15:06 UTC by shraddha761

I tried to Improvised sentence in readme

2023-10-30 15:06 UTC, shraddha761 commented
@roberto-butti please review

2023-10-31 17:20 UTC, shraddha761 commented
@roberto-butti is there any updation required

2023-10-31 17:29 UTC, roberto-butti requested changes

2023-10-31 17:29 UTC, roberto-butti commented on README.md
> +These functions were initially conceived during my exploration of FIT files, which are rich sources of data pertaining to sports activities. Enclosed within these files, you'll discover in-depth info
Thank you for the feedback, suggestion, but I keep the prev version

2023-10-31 17:29 UTC, roberto-butti commented on README.md
> +This package encompasses a diverse set of statistical measures, including mean, mode, median, range, quantiles, first quartile (25th percentile), third quartile (75th percentile), as well as frequenc
please change to this:
The functions provided by this package, cover a range of measures, including mean, mode, median, range, quantiles, first quartile (25th percentile), third quartile (75th percentile), frequency tables  (both cumulative and relative), standard deviation (applicable to both populations and samples), and variance (once again, for populations and samples).

2023-10-31 17:40 UTC, shraddha761 commented
@roberto-butti done with changes

2023-10-31 17:42 UTC, roberto-butti approved these changes

2023-10-31 17:43 UTC, merged